// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdAKad2_ooCatFEOl-t6ik2ddDRrcxKoc',
    appId: '1:858162190081:web:f65798db387b7a8f78ad00',
    messagingSenderId: '858162190081',
    projectId: 'snapshop-4cf42',
    authDomain: 'snapshop-4cf42.firebaseapp.com',
    storageBucket: 'snapshop-4cf42.appspot.com',
    measurementId: 'G-9TD0DZMBFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfzlysJgLZQf5D1PRRxjlyCtnBOZFT8-k',
    appId: '1:858162190081:android:4fde968177f07b3778ad00',
    messagingSenderId: '858162190081',
    projectId: 'snapshop-4cf42',
    storageBucket: 'snapshop-4cf42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOJxH-5oq2cQEootJ5ug19Jj9AC5dHgU',
    appId: '1:858162190081:ios:6dbcc9f9f6e44f9278ad00',
    messagingSenderId: '858162190081',
    projectId: 'snapshop-4cf42',
    storageBucket: 'snapshop-4cf42.appspot.com',
    iosBundleId: 'com.example.snapShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOJxH-5oq2cQEootJ5ug19Jj9AC5dHgU',
    appId: '1:858162190081:ios:6dbcc9f9f6e44f9278ad00',
    messagingSenderId: '858162190081',
    projectId: 'snapshop-4cf42',
    storageBucket: 'snapshop-4cf42.appspot.com',
    iosBundleId: 'com.example.snapShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdAKad2_ooCatFEOl-t6ik2ddDRrcxKoc',
    appId: '1:858162190081:web:4ae335c13a7a2ba678ad00',
    messagingSenderId: '858162190081',
    projectId: 'snapshop-4cf42',
    authDomain: 'snapshop-4cf42.firebaseapp.com',
    storageBucket: 'snapshop-4cf42.appspot.com',
    measurementId: 'G-D4LD90S2F6',
  );
}
